### ISSUE TITLE
你好，想请教一个问题

### ISSUE THREAD

**Issue by lixingwang2019** [Airmole/ShellBox#10]
你好，现在在学小程序，也想做一个类似的简单版小程序，但是卡在了小程序上输入的学号和密码是怎么登入到教务系统的，想请教一下大佬，谢谢

**Comment by Airmole** [comment]
> 你好，现在在学小程序，也想做一个类似的简单版小程序，但是卡在了小程序上输入的学号和密码是怎么登入到教务系统的，想请教一下大佬，谢谢

我这边后端用的是php的curl模拟登录教务系统的。你可以参考这篇文章了解下http://www.zjmainstay.cn/php-curl#%E4%B8%80%E6%A8%A1%E6%8B%9F%E7%99%BB%E5%BD%95%E7%A4%BA%E4%BE%8B

**Comment by lixingwang2019** [comment]
好的，谢谢啦
