### ISSUE TITLE
电费绑定和网费绑定页面ios端渲染错误

### ISSUE THREAD

**Issue by hsmustard** [Airmole/ShellBox#12]
如图所示
![Image text](https://s2.ax1x.com/2020/01/05/lBgjKg.jpg)

**Comment by Airmole** [comment]
> 如图所示
> ![Image text](https://camo.githubusercontent.com/e200ceef7ddcd7a801a6548d300090e0adf9911b/68747470733a2f2f73322e617831782e636f6d2f323032302f30312f30352f6c42676a4b672e6a7067)

手头没有iOS设备，因此也不方便调试解决。你可以去参考一下we重邮项目的login界面代码。我这个项目的这个界面就是移植的we重邮的login扽古界面（https://github.com/lanshan-studio/wecqupt/blob/master/pages/more/login.wxml）
