### ISSUE TITLE
关于功能实现问题

### ISSUE THREAD

**Issue by xiaoming1009** [Airmole/ShellBox#8]
您好我是您的粉丝，我最近在学习微信小程序，我对您的这个小盒子程序非常喜欢，我把它下载下来放入编辑器中但在编辑器中无法登陆此程序，这是为什么呢？打扰您了

**Comment by Airmole** [comment]
> 您好我是您的粉丝，我最近在学习微信小程序，我对您的这个小盒子程序非常喜欢，我把它下载下来放入编辑器中但在编辑器中无法登陆此程序，这是为什么呢？打扰您了

@xiaoming1009 你能详细说明一下吗?最好有截图
